wip

diff --git a/test b/test
--- a/test
+++ b/test
@@ -40,7 +40,7 @@ for suite in "$PWD"/**/{__tests__,*.{test,spec}{,s}}/; do
     stdout="$(bash "$test" 2>>"$actual" | printf "%s\n" "$(cat -)")" || status="$?"
     printf "\nstdout:\n%s\nstatus: %s\n" "$stdout" "$status" >> "$actual"
 
-    if diff --old-group-format="$(tput setaf 12 || :)%<$(tput sgr0 || :)" --new-group-format="$(tput setaf 9 || :)%>$(tput sgr0 || :)" --unchanged-group-format="$(tput setaf 8 || :)%=$(tput sgr0 || :)" --color=auto "$expected" "$actual"; then
+    if diff --old-group-format="$(tput setaf 12  || printf '# MISSING: # \n')%<$(tput sgr0 || :)" --new-group-format="$(tput setaf 9 || printf '# NOT EXPECTED: # \n')%>$(tput sgr0 || :)" --unchanged-group-format="$(tput setaf 8 || printf '# AS EXPECTED: # \n')%=$(tput sgr0 || :)" --color=auto "$expected" "$actual"; then
       passes+=1
     else
       failures+=1
